server:
  port: 8763

#eureka服务端的实例名称
eureka:
  instance:
    hostname: eureka8763.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defautZone: http://eureka8762.com:8762/eureka/,http://eureka8761.com:8761/eureka/
