server:
  port: 8761

#eureka服务端的实例名称
eureka:
  instance:
    hostname: eureka8761.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka8762.com:8762/eureka/,http://eureka8763.com:8763/eureka/
