server:

  port: 9001

spring:
  application:
    name: cloud-ribbon
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: cloud-ribbon
    prefer-ip-address: false